# paired config 
# latent dim 1024, batch size 2048, lr scheduler, large batchsize

rna_config_path: null
ga_config_path: null
rna_checkpoint: null
ga_checkpoint: null
temperature: 0.1
tau: 0.5
freeze_param: False
learning_rate: 1.0e-5
weight_decay: 0.05
warmup_steps: 1000
anneal_steps: 5000
min_lr: 1.0e-6
log_dir: logs
save_dir: saved_models
run_name: paired_config_scratch
num_steps: 5000
device: 'cuda' 
eval_steps: 25
save_steps: 25
batchsize: 4096