# the templeate of pair_eval_config
# user should careful the param:
# eval_id
# rna_config, ga_config, rna_checkpoint_path, ga_checkpoint_path, use_pretrained
# log_dir, save_dir recomment to be the same as the training function will add prefix
# use_pretrained must be the same 

# large, pretrain, 2

eval_id: 2 #1,2,3,4
phase_1_params:
  batch_size: 2048
  rna_config: /home/rsun@ZHANGroup.local/sr_project/saved_models/config_large_2025-02-27-05-24/config.yaml
  ga_config: /home/rsun@ZHANGroup.local/sr_project/saved_models/ga_config_large_2025-02-27-05-24/config.yaml
  rna_checkpoint_path: /home/rsun@ZHANGroup.local/sr_project/saved_models/config_large_2025-02-27-05-24/checkpoint_16000.pth
  ga_checkpoint_path: /home/rsun@ZHANGroup.local/sr_project/saved_models/ga_config_large_2025-02-27-05-24/checkpoint_12000.pth
  use_pretrained: True
  log_dir: logs/large_pretrain_2
  save_dir: saved_models/large_pretrain_2
  training_steps: 1600
  lr: 1.0e-5
  device: "cuda"

phase_2_params:
  batch_size: 2048
  use_pretrained: True
  log_dir: logs/large_pretrain_2
  save_dir: saved_models/large_pretrain_2
  training_steps: 40000
  eval_steps: 400
  save_steps: 10000
  lr: 1.0e-5
  min_lr: 5.0e-6
  warmup_steps: 4000
  anneal_steps: 32000
  device: "cuda"